location: .gitman
sources:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: release/noetic/mavlink/2022.8.8-1
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: lib/mavlink-gbp-release
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/mavlink/mavros.git
    name: mavros
    rev: 1.13.0
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_interface.git
    name: px4_interface
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_interface
    scripts:
      - git submodule update --init --recursive
